<?php

return [
    'GET' => [
        HOME_ROUTE => 'app\controllers\Controller@showHome',
        UMS_HOME_ROUTE => 'app\controllers\UMSBaseController@showUmsHome',
//         USERS_LIST_ROUTE => 'app\controllers\UMSTablesController@showUsersList',
//         USERS_LIST_ROUTE.'/:orderBy' => 'app\controllers\UMSTablesController@showUsersList',
//         USERS_LIST_ROUTE.'/:orderBy/:orderDir' => 'app\controllers\UMSTablesController@showUsersList',
//         USERS_LIST_ROUTE.'/:orderBy/:orderDir/:page' => 'app\controllers\UMSTablesController@showUsersList',
//         USERS_LIST_ROUTE.'/:orderBy/:orderDir/:page/:nRow' => 'app\controllers\UMSTablesController@showUsersList',
        UMS_TABLES_ROUTE => 'app\controllers\UMSTablesController@showTable',
        UMS_TABLES_ROUTE.'/:table' => 'app\controllers\UMSTablesController@showTable',
        UMS_TABLES_ROUTE.'/:table/:orderBy' => 'app\controllers\UMSTablesController@showTable',
        UMS_TABLES_ROUTE.'/:table/:orderBy/:orderDir' => 'app\controllers\UMSTablesController@showTable',
        UMS_TABLES_ROUTE.'/:table/:orderBy/:orderDir/:page' => 'app\controllers\UMSTablesController@showTable',
        UMS_TABLES_ROUTE.'/:table/:orderBy/:orderDir/:page/:nRow' => 'app\controllers\UMSTablesController@showTable',
        USER_ROUTE.'/:user' => 'app\controllers\UMSController@showUser',
//         USER_ROUTE.'/:user/'.DELETE_ROUTE.'/'.CONFIRM_ROUTE => 'app\controllers\UMSController@showDeleteUser',
        USER_ROUTE.'/:user/'.UPDATE_ROUTE => 'app\controllers\UMSController@showUserUpdate',
        USER_ROUTE.'/:user/'.PASS_UPDATE_ROUTE => 'app\controllers\UMSController@showPasswordUpdate',
        USER_ROUTE.'/:user/'.LOCKS_ROUTE => 'app\controllers\UMSController@showLocksUserUpdate',
        DELETED_USER_ROUTE.'/:user' => 'app\controllers\UMSController@showDeletedUser',
        SESSION_ROUTE.'/:session' => 'app\controllers\UMSController@showSession',
        NEW_USER_ROUTE => 'app\controllers\UMSController@showNewUser',
        NEW_EMAIL_ROUTE => 'app\controllers\EmailController@showNewEmail',
        APP_SETTINGS_ROUTE => 'app\controllers\AppSettingsController@showAppSettings',
        APP_SETTINGS_ROUTE.'/:section' => 'app\controllers\AppSettingsController@showAppSettings',
        FAKE_USERS_ROUTE => 'app\controllers\FakeUsersController@showAddFakeUsers',
        RSA_GENERATOR_ROUTE => 'app\controllers\RSAKeyGeneratorController@showRSAKeyGenerator',
        SITE_MAP_GENERATOR_ROUTE => 'app\controllers\SiteMapGeneratorController@showSiteMapGenerator',
        SITE_MAP_UPDATE_ROUTE => 'app\controllers\SiteMapGeneratorController@showSiteMapUpdate',
        ACCOUNT_ENABLER_ROUTE.'/:token' => 'app\controllers\LoginController@enableAccount',
        EMAIL_ENABLER_ROUTE.'/:token' => 'app\controllers\LoginController@enableNewEmail',
        LOGIN_ROUTE => 'app\controllers\LoginController@showLogin',
        SIGNUP_ROUTE => 'app\controllers\LoginController@showSignup',
        SIGNUP_ROUTE.'/'.CONFIRM_ROUTE => 'app\controllers\LoginController@showSignupConfirm',
        PASS_RESET_REQ_ROUTE => 'app\controllers\LoginController@showPasswordResetRequest',
        PASS_RESET_ROUTE.'/:token' => 'app\controllers\LoginController@showPasswordReset',
        ACCOUNT_INFO_ROUTE => 'app\controllers\AccountController@showAccountInfo',
        ACCOUNT_SETTINGS_ROUTE => 'app\controllers\AccountController@showAccountSettings',
        ACCOUNT_SETTINGS_ROUTE.'/'.PASS_UPDATE_ROUTE => 'app\controllers\AccountController@showChangePassword',
        ACCOUNT_SETTINGS_ROUTE.'/'.DELETE_ROUTE.'/'.CONFIRM_ROUTE => 'app\controllers\AccountController@showDeleteAccount',
        GET_JSON_CONFIG_ROUTE => function () {
            sendJsonResponse([
                'minLengthName' => MIN_LENGTH_NAME,
                'maxLengthName' => MAX_LENGTH_NAME,
                'minLengthUsername' => MIN_LENGTH_USERNAME,
                'maxLengthUsername' => MAX_LENGTH_USERNAME,
                'minLengthEmail' => MIN_LENGTH_EMAIL,
                'maxLengthEmail' => MAX_LENGTH_EMAIL,
                'minLengthPassword' => MIN_LENGTH_PASS,
                'maxLengthPassword' => MAX_LENGTH_PASS,
                'useRegexName' => USE_REGEX_NAME,
                'regexName' => modifyRegexJS(REGEX_NAME),
                'useRegexUsername' => USE_REGEX_USERNAME,
                'regexUsername' => modifyRegexJS(REGEX_USERNAME),
                'useRegexEmail' => USE_REGEX_EMAIL,
                'regexEmail' => modifyRegexJS(REGEX_EMAIL),
                'useRegexPassword' => USE_REGEX_PASSWORD,
                'regexPassword' => modifyRegexJS(REGEX_PASSWORD)
            ]);
        }
    ],

    'POST' => [
        NEW_USER_ROUTE => 'app\controllers\UMSController@newUser',
        USER_ROUTE.'/'.UPDATE_ROUTE => 'app\controllers\UMSController@userUpdate',
        USER_ROUTE.'/'.PASS_UPDATE_ROUTE => 'app\controllers\UMSController@passwordUpdate',
        USER_ROUTE.'/'.RESET_LOCK_COUNTERS_ROUTE => 'app\controllers\UMSController@resetWrongPasswords',
        USER_ROUTE.'/'.DELETE_ROUTE => 'app\controllers\UMSController@deleteUser',
//         USER_ROUTE.'/update/reset/lock' => 'app\controllers\UMSController@resetLockUser',
//         'ums/user/delete/new/email' => 'app\controllers\UMSController@deleteNewEmail',
        APP_SETTINGS_ROUTE.'/:section/'.UPDATE_ROUTE => 'app\controllers\AppSettingsController@updateSettings',
        RSA_GENERATOR_ROUTE.'/'.SAVE_ROUTE => 'app\controllers\RSAKeyGeneratorController@generateSaveRsaKey',
        RSA_GENERATOR_ROUTE.'/'.GET_ROUTE => 'app\controllers\RSAKeyGeneratorController@generateRsaKey',
        SITE_MAP_GENERATOR_ROUTE => 'app\controllers\SiteMapGeneratorController@generateSiteMap',
        SEND_EMAIL_ROUTE => 'app\controllers\EmailController@sendEmail',
        FAKE_USERS_ROUTE => 'app\controllers\FakeUsersController@addFakeUsers',
        LOGIN_ROUTE => 'app\controllers\LoginController@login',
        SIGNUP_ROUTE => 'app\controllers\LoginController@signup',
        SIGNUP_ROUTE.'/'.RESEND_EMAIL_ROUTE => 'app\controllers\LoginController@signupResendEmail',
        LOGOUT_ROUTE => 'app\controllers\LoginController@logout',
        PASS_RESET_REQ_ROUTE => 'app\controllers\LoginController@passwordResetRequest',
        PASS_RESET_ROUTE => 'app\controllers\LoginController@passwordReset',
        ACCOUNT_SETTINGS_ROUTE.'/'.UPDATE_ROUTE => 'app\controllers\AccountController@updateAccount',
        ACCOUNT_SETTINGS_ROUTE.'/'.PASS_UPDATE_ROUTE => 'app\controllers\AccountController@changePassword',
        ACCOUNT_SETTINGS_ROUTE.'/'.DELETE_ROUTE => 'app\controllers\AccountController@deleteAccount',
        ACCOUNT_SETTINGS_ROUTE.'/'.RESEND_EMAIL_ROUTE => 'app\controllers\AccountController@resendEmailEnabler',
        ACCOUNT_SETTINGS_ROUTE.'/'.DELETE_EMAIL_ROUTE => 'app\controllers\AccountController@deleteNewEmail',
        GET_JSON_KEY_ROUTE => 'app\controllers\Controller@showKeyJSON'
    ]
];
